# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1POSVqO8nIpcAzAbnQvtYgavcJuUoBp2j
"""

print('hello')