include ':blocklylib-vertical'
include ':blocklylib-core'
project(':blocklylib-core').projectDir = new File(rootDir, 'blocklylib-core')
include ':app'
include ':PhysicaloidLibrary'
project(':PhysicaloidLibrary').projectDir = new File(rootDir, 'PhysicaloidLibrary/')
rootProject.name = "learn4"

dependencyResolutionManagement{
    repositories{
        maven { url "https://jitpack.io" }
    }
}
